apiVersion: v1
kind: Service
metadata:  
  name: envoy-svc
  namespace: kube-system
spec:
  selector:    
    app: envoy
  type: LoadBalancer
  ports:  
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP